{% set name = "pyppmd" %}
{% set version = "0.17.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05a4765833623d5cc1c9afc27d9b05fb64f0319711beffe0b44d9695eb1beb0a

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools >=45.0
    - setuptools-scm >=6.0.1
  run:
    - python
    - importlib_metadata

test:
  imports:
    - pyppmd
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miurahr/pyppmd
  summary: PPMd compression/decompression library
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - sarthakpati
